version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3013 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3013:3013"
    env_file:
      - .env
    environment:
      BUTTER_TOKEN: "${BUTTER_TOKEN}"
      MAILCHIMP_API_TOKEN: "${MAILCHIMP_API_TOKEN}"
      MAILCHIMP_API_SERVER: "https://us1.api.mailchimp.com/3.0"
      MAILCHIMP_LIST_ID: "${MAILCHIMP_LIST_ID}"
